# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0003_auto_20191125_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rates',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='rates',
            unique_together=set([('user', 'design', 'usability', 'content', 'project')]),
        ),
        migrations.AlterIndexTogether(
            name='rates',
            index_together=set([('user', 'design', 'usability', 'content', 'project')]),
        ),
    ]
